# Generated by Django 5.1.4 on 2024-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='complete',
        ),
        migrations.AlterField(
            model_name='message',
            name='week',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
