# Generated by Django 5.1.4 on 2024-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
