# Generated by Django 5.1.4 on 2024-12-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_selectedyear_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='year',
            field=models.TextField(default=2024),
            preserve_default=False,
        ),
    ]
